spec:
  template:
    spec:
      containers:
      - env:
        - name: PORT
          value: 8080
        - name: TENANT_ID
          value: REPLACE_WITH_TENANT_ID      
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /actuator/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2

