apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
spec:
  template:
    spec:
      containers:
        - env:
          - name: PORT
            value: '8080'
          - name: BFF_URL
            value: http://modern-bff-cloudready-security.apps-crc.testing
          livenessProbe:
            failureThreshold: 12
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2         
