
debug: false
---
server:
  port: ${PORT:8080}
  servlet:
    session:
       cookie:
          name: '${session_cookie:MYSESSIONID}'

logging:
  level:
    org.springframework:
      # security: DEBUG
      session: INFO

app:
   uiRedirectUri: '${UI_REDIRECT_URI:http://localhost:4200}'
   resourceMSUri: '${RESOURCE_MS_URI:http://localhost:9000}'
   security:
      allowedOrigins:
      - '${app.uiRedirectUri}'

security:
  oauth2:
    client:
      client-id: '${CLIENT_ID}'
      client-secret: '${CLIENT_SECRET}'
      accessTokenUri: ${OAUTH_SERVER_URL}/token
      userAuthorizationUri: ${OAUTH_SERVER_URL}/authorization
    resource:
      userInfoUri: ${OAUTH_SERVER_URL}/userinfo

#enable the actuator endpoints for health, metrics, and prometheus.
management.endpoints.web.exposure.include: health,metrics,prometheus,liveness
